services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./gutendex.dump:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn gutenberg_app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data:
